# Generated by Django 4.0.4 on 2022-05-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
