# Generated by Django 4.0.4 on 2022-05-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_paymentrequest_delete_payrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
