# Generated by Django 4.0.4 on 2022-05-29 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rrequest_delete_reimbursementrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payable_to', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='RRequest',
        ),
    ]
