# Generated by Django 4.0.4 on 2022-05-30 18:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_reimbursementrequest_delete_payrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='reReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payable_to', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ReimbursementRequest',
        ),
    ]
