# Generated by Django 4.0.4 on 2022-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reimbursementrequest_delete_rereimbursementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementrequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
