# Generated by Django 4.0.4 on 2022-08-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_reimbursementrequest_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='receipt',
            field=models.ImageField(default=False, upload_to='receipts'),
        ),
    ]
